<?php

declare(strict_types=1);

namespace Nexus\Docker;

final class DockerComposeGenerator
{
    /** @return array<string, string> */
    public function files(DockerConfig $config): array
    {
        return [
            'compose.yaml' => $this->compose($config),
            'docker/php/Dockerfile' => $this->dockerfile($config->runtime),
            '.dockerignore' => ".git\nvendor\nnode_modules\nvar/cache\n.env\n",
        ];
    }

    public function compose(DockerConfig $config): string
    {
        $services = [
            'app' => $this->appService($config->runtime),
        ];

        foreach ($config->services as $service) {
            $services[$service->value] = $this->service($service);
        }

        $yaml = "name: nexus-app\nservices:\n";
        foreach ($services as $name => $lines) {
            $yaml .= "  {$name}:\n";
            foreach ($lines as $line) {
                $yaml .= "    {$line}\n";
            }
        }

        if ($config->production) {
            $yaml .= "\n# Production profile generated by Nexus. Review secrets and resource limits before deployment.\n";
        }

        return $yaml;
    }

    /** @return list<string> */
    private function appService(DockerRuntime $runtime): array
    {
        $port = $runtime === DockerRuntime::PhpFpmNginx ? '8080:80' : '8080:8080';

        return [
            'build:',
            '  context: .',
            '  dockerfile: docker/php/Dockerfile',
            'working_dir: /app',
            'volumes:',
            '  - .:/app',
            'ports:',
            "  - \"{$port}\"",
        ];
    }

    /** @return list<string> */
    private function service(DockerService $service): array
    {
        return match ($service) {
            DockerService::Postgres => ['image: postgres:18-alpine', 'environment:', '  POSTGRES_DB: nexus', '  POSTGRES_USER: nexus', '  POSTGRES_PASSWORD: nexus', 'ports:', '  - "5432:5432"'],
            DockerService::MySql => ['image: mysql:8.4', 'environment:', '  MYSQL_DATABASE: nexus', '  MYSQL_USER: nexus', '  MYSQL_PASSWORD: nexus', '  MYSQL_ROOT_PASSWORD: root', 'ports:', '  - "3306:3306"'],
            DockerService::Redis => ['image: redis:8-alpine', 'ports:', '  - "6379:6379"'],
            DockerService::Mongo => ['image: mongo:8', 'ports:', '  - "27017:27017"'],
            DockerService::SqlServer => ['image: mcr.microsoft.com/mssql/server:2025-latest', 'environment:', '  ACCEPT_EULA: "Y"', '  MSSQL_SA_PASSWORD: "ChangeMe_Nexus123!"', 'ports:', '  - "1433:1433"'],
            DockerService::RabbitMq => ['image: rabbitmq:4-management-alpine', 'ports:', '  - "5672:5672"', '  - "15672:15672"'],
            DockerService::Kafka => ['image: apache/kafka:4.1.0', 'ports:', '  - "9092:9092"'],
            DockerService::Mailpit => ['image: axllent/mailpit:latest', 'ports:', '  - "1025:1025"', '  - "8025:8025"'],
        };
    }

    private function dockerfile(DockerRuntime $runtime): string
    {
        return match ($runtime) {
            DockerRuntime::FrankenPhp => "FROM dunglas/frankenphp:php8.4\nWORKDIR /app\nCOPY --from=composer:2 /usr/bin/composer /usr/bin/composer\nCMD [\"frankenphp\", \"php-server\", \"--listen=:8080\", \"--root=public\"]\n",
            DockerRuntime::PhpFpmNginx => "FROM php:8.4-fpm-alpine\nWORKDIR /app\nCOPY --from=composer:2 /usr/bin/composer /usr/bin/composer\nCMD [\"php-fpm\", \"-F\"]\n",
            DockerRuntime::RoadRunner => "FROM php:8.4-cli-alpine\nWORKDIR /app\nCOPY --from=composer:2 /usr/bin/composer /usr/bin/composer\nCMD [\"php\", \"bin/nexus\", \"serve\", \"--host=0.0.0.0\", \"--port=8080\"]\n",
            DockerRuntime::OpenSwoole => "FROM php:8.4-cli-alpine\nWORKDIR /app\nCOPY --from=composer:2 /usr/bin/composer /usr/bin/composer\nCMD [\"php\", \"bin/nexus\", \"serve\", \"--host=0.0.0.0\", \"--port=8080\"]\n",
        };
    }
}
