<?php

declare(strict_types=1);

require dirname(__DIR__, 2) . '/vendor/autoload.php';

use Nexus\Database\ConnectionFactory;
use Nexus\Database\DatabaseConfig;

$driver = getenv('DB_DRIVER') ?: '';
$host = getenv('DB_HOST') ?: '127.0.0.1';
$port = (int) (getenv('DB_PORT') ?: 0);
$database = getenv('DB_DATABASE') ?: '';
$username = getenv('DB_USERNAME') ?: null;
$password = getenv('DB_PASSWORD') ?: null;

if (!in_array($driver, ['pgsql', 'mysql', 'sqlsrv', 'oci'], true)) {
    throw new RuntimeException('DB_DRIVER must be pgsql, mysql, sqlsrv or oci.');
}

$driverOptions = $driver === 'sqlsrv'
    ? ['Encrypt' => true, 'TrustServerCertificate' => true]
    : [];

$config = new DatabaseConfig(
    $driver,
    $database,
    $host,
    $port > 0 ? $port : null,
    $username,
    $password,
    driverOptions: $driverOptions,
);

$connection = (new ConnectionFactory())->make($config);

$healthSql = $driver === 'oci' ? 'SELECT 1 AS nexus_health FROM DUAL' : 'SELECT 1 AS nexus_health';
$health = $connection->select($healthSql);
$healthRow = $health[0] ?? [];
$healthValue = array_values($healthRow)[0] ?? null;
if (!is_int($healthValue) && !is_float($healthValue) && !is_string($healthValue)) {
    throw new RuntimeException(sprintf('%s health query returned an invalid value.', $driver));
}
if ((int) $healthValue !== 1) {
    throw new RuntimeException(sprintf('%s health query failed.', $driver));
}

$table = 'nexus_rc05_probe';
$dropSql = match ($driver) {
    'pgsql' => "DROP TABLE IF EXISTS {$table}",
    'mysql' => "DROP TABLE IF EXISTS {$table}",
    'sqlsrv' => "IF OBJECT_ID('{$table}', 'U') IS NOT NULL DROP TABLE {$table}",
    'oci' => "BEGIN EXECUTE IMMEDIATE 'DROP TABLE {$table}'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;",
};
$createSql = match ($driver) {
    'pgsql' => "CREATE TABLE {$table} (id BIGSERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL)",
    'mysql' => "CREATE TABLE {$table} (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL)",
    'sqlsrv' => "CREATE TABLE {$table} (id BIGINT IDENTITY(1,1) PRIMARY KEY, name NVARCHAR(100) NOT NULL)",
    'oci' => "CREATE TABLE {$table} (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR2(100) NOT NULL)",
};

$connection->statement($dropSql);
$connection->statement($createSql);

if ($driver === 'oci') {
    $connection->statement("INSERT INTO {$table} (name) VALUES (:name)", ['name' => 'Nexus']);
} else {
    $connection->statement("INSERT INTO {$table} (name) VALUES (?)", ['Nexus']);
}

$rows = $connection->select("SELECT name FROM {$table}");
$nameRow = $rows[0] ?? [];
$nameValue = array_values($nameRow)[0] ?? null;
if ($nameValue !== 'Nexus') {
    throw new RuntimeException(sprintf('%s insert/select probe failed.', $driver));
}

$connection->statement($dropSql);

fwrite(STDOUT, sprintf("RC-05 %s live integration OK\n", $driver));
